checks:
  return-statements:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
  similar-code:
    enabled: false
engines:
  eslint:
    enabled: true
    config: .eslintrc
  fixme:
      enabled: true
ratings:
  paths:
  - "**.js"