checks:
  return-statements:
    enabled: false
  method-complexity:
    enabled: false
  method-length:
    enabled: false
engines:
  eslint:
    enabled: true
    config: .eslintrc
  fixme:
      enabled: true
ratings:
  paths:
  - "**.js"